#include "weather_codes.h"
#include <Arduino.h>

struct WeatherCodeText {
    int code;
    const char* text;
};

static const WeatherCodeText weatherTable[] PROGMEM = {
    {0, "Molnens utveckling har icke kunnat observeras eller icke observerats"},
    {1, "Moln har upplösts helt eller avtagit i utsträckning, i mäktighet eller i täthet"},
    {2, "Molnhimlen i stort sett oförändrad"},
    {3, "Moln har bildats eller tilltagit i utsträckning, i mäktighet eller i täthet"},
    {4, "Sikten nedsatt av brandrök eller fabriksrök"},
    {5, "Torrdis (solrök)"},
    {6, "Stoft svävar i luften"},
    {7, "Stoft eller sand uppvirvlas av vinden"},
    {8, "Utpräglad stoft- eller sandvirvel"},
    {9, "Sandstorm under senaste timmen eller inom synhåll"},
    {10, "Fuktdis 1–10 km"},
    {11, "Låg dimma i bankar"},
    {12, "Sammanhängande låg dimma"},
    {13, "Kornblixt"},
    {14, "Fallstrimmor (nederbörd som ej når marken)"},
    {15, "Nederbörd >5 km från stationen"},
    {16, "Nederbörd <5 km från stationen men ej på stationen"},
    {17, "Åska utan nederbörd på stationen"},
    {18, "Starka vindbyar"},
    {19, "Skydrag eller tromb"},
    {20, "Duggregn eller kornsnö senaste timmen"},
    {21, "Regn senaste timmen"},
    {22, "Snöfall senaste timmen"},
    {23, "Snöblandat regn senaste timmen"},
    {24, "Underkylt regn senaste timmen"},
    {25, "Regnskurar senaste timmen"},
    {26, "Snöbyar senaste timmen"},
    {27, "Hagelbyar senaste timmen"},
    {28, "Dimma senaste timmen"},
    {29, "Åska senaste timmen"},
    {30, "Sandstorm avtagit"},
    {31, "Sandstorm oförändrad"},
    {32, "Sandstorm tilltagit"},
    {33, "Kraftig sandstorm avtagit"},
    {34, "Kraftig sandstorm oförändrad"},
    {35, "Kraftig sandstorm tilltagit"},
    {36, "Lågt lätt/måttligt snödrev"},
    {37, "Lågt tätt snödrev"},
    {38, "Högt lätt/måttligt snödrev"},
    {39, "Högt tätt snödrev"},
    {40, "Dimma inom synhåll"},
    {41, "Dimma i bankar"},
    {42, "Dimma lättare senaste timmen"},
    {43, "Dimma utan skymt av himlen lättare"},
    {44, "Dimma oförändrad"},
    {45, "Dimma utan skymt oförändrad"},
    {46, "Dimma med skymt tilltagit"},
    {47, "Dimma utan skymt tilltagit"},
    {48, "Underkyld dimma, skymt"},
    {49, "Underkyld dimma, utan skymt"},
    {50, "Lätt duggregn med avbrott"},
    {51, "Lätt duggregn ihållande"},
    {52, "Måttligt duggregn med avbrott"},
    {53, "Måttligt duggregn ihållande"},
    {54, "Tätt duggregn med avbrott"},
    {55, "Tätt duggregn ihållande"},
    {56, "Lätt underkylt duggregn"},
    {57, "Måttligt/tätt underkylt duggregn"},
    {58, "Lätt duggregn + regn"},
    {59, "Måttligt/tätt duggregn + regn"},
    {60, "Lätt regn med avbrott"},
    {61, "Lätt regn ihållande"},
    {62, "Måttligt regn med avbrott"},
    {63, "Måttligt regn ihållande"},
    {64, "Starkt regn med avbrott"},
    {65, "Starkt regn ihållande"},
    {66, "Lätt underkylt regn"},
    {67, "Måttligt/starkt underkylt regn"},
    {68, "Lätt regn/duggregn + snö"},
    {69, "Måttligt/starkt regn/duggregn + snö"},
    {70, "Snöfall"},
    {71, "Lätt snöfall"},
    {72, "Måttligt snöfall"},
    {73, "Måttligt snöfall ihållande"},
    {74, "Tätt snöfall med avbrott"},
    {75, "Tätt snöfall ihållande"},
    {76, "Isnålar"},
    {77, "Kornsnö"},
    {78, "Enstaka snöstjärnor"},
    {79, "Iskorn"},
    {80, "Lätta regnskurar"},
    {81, "Måttliga/kraftiga regnskurar"},
    {82, "Skyfall"},
    {83, "Lätt snöblandat regn i byar"},
    {84, "Måttligt/kraftigt snöblandat regn i byar"},
    {85, "Lätta snöbyar"},
    {86, "Måttliga/kraftiga snöbyar"},
    {87, "Lätta småhagelbyar"},
    {88, "Kraftiga småhagelbyar"},
    {89, "Lätta ishagelbyar"},
    {90, "Måttliga/kraftiga ishagelbyar"},
    {91, "Lätt regn + åska på avstånd"},
    {92, "Måttligt/starkt regn + åska på avstånd"},
    {93, "Lätt snöfall eller hagel + åska på avstånd"},
    {94, "Starkt snöfall eller hagel + åska på avstånd"},
    {95, "Svagt/måttligt åskväder utan hagel"},
    {96, "Svagt/måttligt åskväder med hagel"},
    {97, "Kraftigt åskväder utan hagel"},
    {98, "Kraftigt åskväder med sandstorm"},
    {99, "Kraftigt åskväder med hagel"},
    {100, "Inget signifikant väder"},
    {101, "Moln har upplösts senaste timmen"},
    {102, "Moln oförändrat senaste timmen"},
    {103, "Moln tilltagit senaste timmen"},
    {104, "Dis/rök/stoft ≥1 km"},
    {105, "Dis/rök/stoft <1 km"},
    {110, "Fuktdis 1–10 km"},
    {111, "Isnålar"},
    {112, "Blixt på avstånd"},
    {118, "Starka vindbyar"},
    {120, "Dimma"},
    {121, "Nederbörd"},
    {122, "Duggregn eller kornsnö"},
    {123, "Regn"},
    {124, "Snöfall"},
    {125, "Underkylt regn/duggregn"},
    {126, "Åskväder"},
    {127, "Snödrev eller sandstorm"},
    {128, "Snödrev/sandstorm, sikt ≥1 km"},
    {129, "Snödrev/sandstorm, sikt <1 km"},
    {130, "Dimma"},
    {131, "Dimma i bankar"},
    {132, "Dimma lättare senaste timmen"},
    {133, "Dimma oförändrad"},
    {134, "Dimma tilltagit"},
    {135, "Underkyld dimma"},
    {140, "Nederbörd"},
    {141, "Lätt/måttlig nederbörd"},
    {142, "Kraftig nederbörd"},
    {143, "Flytande nederbörd, lätt/måttlig"},
    {144, "Flytande nederbörd, kraftig"},
    {145, "Fast nederbörd, lätt/måttlig"},
    {146, "Fast nederbörd, kraftig"},
    {147, "Underkyld nederbörd, lätt/måttlig"},
    {148, "Underkyld nederbörd, kraftig"},
    {150, "Duggregn"},
    {151, "Lätt duggregn"},
    {152, "Måttligt duggregn"},
    {153, "Tätt duggregn"},
    {154, "Lätt underkylt duggregn"},
    {155, "Måttligt underkylt duggregn"},
    {156, "Tätt duggregn"},
    {157, "Lätt duggregn med regn"},
    {158, "Måttligt/tätt duggregn med regn"},
    {160, "Regn"},
    {161, "Lätt regn"},
    {162, "Måttligt regn"},
    {163, "Starkt regn"},
    {164, "Lätt underkylt regn"},
    {165, "Måttligt underkylt regn"},
    {166, "Starkt underkylt regn"},
    {167, "Lätt regn/duggregn med snö"},
    {168, "Måttligt/starkt regn/duggregn med snö"},
    {170, "Snöfall"},
    {171, "Lätt snöfall"},
    {172, "Måttligt snöfall"},
    {173, "Tätt snöfall"},
    {174, "Lätt småhagel"},
    {175, "Måttligt småhagel"},
    {176, "Kraftigt småhagel"},
    {177, "Kornsnö"},
    {178, "Isnålar"},
    {180, "Regnskurar"},
    {181, "Lätta regnskurar"},
    {182, "Måttliga regnskurar"},
    {183, "Kraftiga regnskurar"},
    {184, "Skyfall"},
    {185, "Lätta snöbyar"},
    {186, "Måttliga snöbyar"},
    {187, "Kraftiga snöbyar"},
    {189, "Hagel"},
    {190, "Åskväder"},
    {191, "Åska utan nederbörd"},
    {192, "Åska med regn/snöbyar"},
    {193, "Åska med hagel"},
    {194, "Kraftigt åskväder utan nederbörd"},
    {195, "Kraftigt åskväder med regnskurar/snöbyar"},
    {196, "Kraftigt åskväder med hagel"},
    {199, "Tromb eller tornado"},
    {204, "Vulkanaska"},
    {206, "Tjockt stoftdis"},
    {207, "Vattenstänk pga blåst"},
    {208, "Drivande stoft"},
    {209, "Haboob (kraftig stoftstorm på avstånd)"},
    {210, "Snödis"},
    {211, "Snöstorm/kraftigt snödrev"},
    {213, "Blixt till marken"},
    {217, "Åska utan regn"},
    {219, "Tromb/tornado inom synhåll"},
    {220, "Avlagring av vulkanaska"},
    {221, "Avlagring av stoft/sand"},
    {222, "Dagg"},
    {223, "Blötsnöutfällning"},
    {224, "Lätt/måttlig dimfrost"},
    {225, "Kraftig dimfrost"},
    {226, "Rimfrost"},
    {227, "Kraftig isbeläggning"},
    {228, "Isskorpa"},
    {230, "Stoft-/sandstorm under fryspunkten"},
    {239, "Kraftigt snödrev/snöfall"},
    {241, "Dimma till havs"},
    {242, "Dimma i dalgång"},
    {243, "Sjörök i Arktis/Antarktis"},
    {244, "Advektionsdimma över vatten"},
    {245, "Advektionsdimma över land"},
    {246, "Dimma över is/snö"},
    {247, "Tät dimma 60–90 m"},
    {248, "Tät dimma 30–60 m"},
    {249, "Tät dimma <30 m"},
    {250, "Duggregn <0.10 mm/h"},
    {251, "Duggregn 0.10–0.19 mm/h"},
    {252, "Duggregn 0.20–0.39 mm/h"},
    {253, "Duggregn 0.40–0.79 mm/h"},
    {254, "Duggregn 0.80–1.59 mm/h"},
    {255, "Duggregn 1.60–3.19 mm/h"},
    {256, "Duggregn 3.20–6.39 mm/h"},
    {257, "Duggregn >6.40 mm/h"},
    {259, "Duggregn + snöfall"},
    {260, "Regn <1.0 mm/h"},
    {261, "Regn 1.0–1.9 mm/h"},
    {262, "Regn 2.0–3.9 mm/h"},
    {263, "Regn 4.0–7.9 mm/h"},
    {264, "Regn 8.0–15.9 mm/h"},
    {265, "Regn 16.0–31.9 mm/h"},
    {266, "Regn 32.0–63.9 mm/h"},
    {267, "Regn >64.0 mm/h"},
    {270, "Snö <1.0 cm/h"},
    {271, "Snö 1.0–1.9 cm/h"},
    {272, "Snö 2.0–3.9 cm/h"},
    {273, "Snö 4.0–7.9 cm/h"},
    {274, "Snö 8.0–15.9 cm/h"},
    {275, "Snö 16.0–31.9 cm/h"},
    {276, "Snö 32.0–63.9 cm/h"},
    {277, "Snö >64.0 cm/h"},
    {278, "Snöfall eller isnålar från klar himmel"},
    {279, "Frysande blötsnö"},
    {280, "Regn"},
    {281, "Underkylt regn"},
    {282, "Snöblandat regn"},
    {283, "Snöfall"},
    {284, "Småhagel/snöhagel"},
    {285, "Småhagel/snöhagel + regn"},
    {286, "Småhagel/snöhagel + snöblandat regn"},
    {287, "Småhagel/snöhagel + snö"},
    {288, "Hagel"},
    {289, "Hagel + regn"},
    {290, "Hagel + snöblandat regn"},
    {291, "Hagel + snö"},
    {292, "Skurar/åska till havs"},
    {293, "Skurar/åska över berg"},
    {508, "Inga signifikanta fenomen"},
    {509, "Ingen observation – data saknas"},
    {510, "Väder saknas men förväntades"},
    {511, "Saknat värde"},
};

static const int weatherCount = sizeof(weatherTable) / sizeof(weatherTable[0]);

const char* decodeWeather(int code) {
    for (int i = 0; i < weatherCount; i++) {
        WeatherCodeText entry;
        memcpy_P(&entry, &weatherTable[i], sizeof(entry));
        if (entry.code == code) {
            return entry.text;
        }
    }
    return "Okänd kod";
}
